#!/usr/bin/env bash

# Path
test_dir='test'
test_tmp="$test_dir/tmp"

# ANSI
bold="\e[1m"
fg_red="\e[31m"
fg_green="\e[32m"
reset_all="\e[0m"
pass="${bold}${fg_green}[pass]${reset_all}"
fail="${bold}${fg_red}[fail]${reset_all}"

# Run tests and display results
for test in $(find $test_dir -name "test_*" | sort); do
    # Run test and redirect output to a temporary file
    $test > $test_tmp
    # Record the exit status
    exit_status=$?
    # Get test name
    test_name="${bold}$(basename $test | sed 's/_/ /g')${reset_all}"
    # Check the exit status
    if [[ $exit_status -eq 0 ]]; then
        printf "${pass} ${test_name}\n"
    else
        printf "${fail} ${test_name}\n"
        # Print the testcase output from temporary file
        if [[ -s $test_tmp ]]; then
            cat $test_tmp | sed 's/^/       /'
        else
            echo "       Testcase failed to run"
        fi
    fi

    # Clean up
    [[ -f $test_tmp ]] && rm $test_tmp
    pkill -9 -f "./daemon.py"
done
