#!/usr/bin/env bash

################################################################################
# Tests if the daemon script correctly creates the database file and the
# link (index) file. The content of the link file should equal to the path to
# database file.
#
# Error codes:
# 0 - Pass
# 1 - Database file not created correctly
# 2 - Link file not created correctly
# 3 - Link file content mismatch
################################################################################

db_path="${PWD}/datebase${RANDOM}.csv"
link_path='/tmp/calendar_link'

clean() {
    [[ -e $db_path ]] && rm $db_path
    [[ -e $link_path ]] && rm $link_path
}

clean_exit() {
    clean
    exit $1
}

clean

./daemon.py $db_path &
sleep .1  # allow daemon to prepare

if [[ ! -f $db_path ]]; then
    echo "Path $db_path does not exist or is not a regular file"
    clean_exit 1
fi

if [[ ! -f $link_path ]]; then
    echo "Path $link_path does not exist or is not a regular file"
    clean_exit 2
fi
if [[ ! $(cat $link_path) = $db_path ]]; then
    echo "Path $link_path not as expected"
    clean_exit 3
fi

clean_exit
