#!/usr/bin/env bash

test_dir="$(dirname $0)"
ori_db="$test_dir/cald_db.csv"
tmp_db="$test_dir/tmp_cald_db.csv"
exp_db="$test_dir/expect_cald_db.csv"
tmp_out="$test_dir/out"
tmp_err="$test_dir/err"
exp_out="$test_dir/expect_out"
exp_err="$test_dir/expect_err"

clean_exit() {
    rm $tmp_out $tmp_err $tmp_db
    exit $1
}

cp $ori_db $tmp_db > /dev/null 2>&1

./daemon.py $tmp_db &

sleep .1

python3 calendar.py ADD >> $tmp_out 2>> $tmp_err
python3 calendar.py ADD "15-10-2021" >> $tmp_out 2>> $tmp_err
python3 calendar.py ADD "15 10 2021" "Description-less event" >> $tmp_out 2>> $tmp_err
python3 calendar.py ADD "15-10-2021" "Description-less event" >> $tmp_out 2>> $tmp_err
python3 calendar.py ADD "15-10-2021" "Event 1" "Description for Event 1" >> $tmp_out 2>> $tmp_err

if ! diff $tmp_db $exp_db; then
    echo "Database differ from expectation!"
    clean_exit 1
fi

if ! diff $tmp_out $exp_out; then
    echo "Stdout differ from expectation!"
    clean_exit 1
fi

if ! diff $tmp_err $exp_err; then
    echo "Stderr differ from expectation!"
    clean_exit 1
fi

clean_exit
