#!/usr/bin/env bash

test_dir="$(dirname $0)"
db_path="$test_dir/cald_db.csv"
tmp_out="$test_dir/out"
tmp_err="$test_dir/err"
exp_out="$test_dir/expect_out"
exp_err="$test_dir/expect_err"

clean_exit() {
    rm $tmp_out $tmp_err
    exit $1
}

./daemon.py $db_path &

sleep .1

python3 calendar.py GET INTERVAL >> $tmp_out 2>> $tmp_err
python3 calendar.py GET INTERVAL 16-10-2021 >> $tmp_out 2>> $tmp_err
python3 calendar.py GET INTERVAL "15 10 2021" 15-10-2021 >> $tmp_out 2>> $tmp_err
python3 calendar.py GET INTERVAL 16-10-2021 15-10-2021 >> $tmp_out 2>> $tmp_err

python3 calendar.py GET INTERVAL 15-10-2021 16-10-2021 >> $tmp_out 2>> $tmp_err
python3 calendar.py GET INTERVAL 14-10-2021 17-10-2021 >> $tmp_out 2>> $tmp_err
python3 calendar.py GET INTERVAL 15-10-1921 16-10-1921 >> $tmp_out 2>> $tmp_err

if ! diff $tmp_out $exp_out; then
    echo "Stdout differ from expectation!"
    clean_exit 1
fi

if ! diff $tmp_err $exp_err; then
    echo "Stderr differ from expectation!"
    clean_exit 1
fi

clean_exit
