name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - '*.py'
      - 'build/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - '*.py'
      - 'build/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cald_on_alpine:$(date +%s)
