name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - '*.py'
      - 'build/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - '*.py'
      - 'build/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build a Docker image
      run: docker build . --file docker/Dockerfile --tag cald:github
    - name: Run a Docker container
      run: docker run -v /sys/fs/cgroup --name cald cald:github sh -c "sleep .1; calendar"
